---
booktitle: Proceedings of the Thirteenth International Conference on Artificial Intelligence
  and Statistics
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
month: 0
publisher: JMLR Workshop and Conference Proceedings
volume: 9
logo: SAIS_logo.jpg
year: '2010'
start: 2010-05-13
end: 2010-05-15
published: 2010-03-31
shortname: AISTATS 2010
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: TehAISTATS2010
cycles: false
editor:
- given: Yee Whye
  family: Teh
- given: Mike
  family: Titterington
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Thirteenth International Conference on Artificial Intelligence and Statistics
    Held in Chia Laguna Resort, Sardinia, Italy on 13-15 May 2010

  Published as Volume 9 by the Proceedings of Machine Learning Research on 31 March 2010.

  Volume Edited by:
    Yee Whye Teh
    Mike Titterington

  Series Editors:
    Neil D. Lawrence
date_str: 13--15 May
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v9"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v9
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
conference:
  name: Proceedings of the Thirteenth International Conference on Artificial Intelligence
    and Statistics
  url: http://aistats.org/aistats2010/
  location: Chia Laguna Resort, Sardinia, Italy
  dates:
  - 2010-05-13
  - 2010-05-14
  - 2010-05-15
  number: 13
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
